[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
base-mainnet = "${BASE_MAINNET_RPC_URL}"

# Voir toutes les options : https://github.com/foundry-rs/foundry